name: Deploy to S3

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0" # Specify your Flutter version

      - name: Navigate to Flutter project directory
        working-directory: helg9000_clock
        run: echo "Navigating to Flutter project directory"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Sync files to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          S3_BUCKET_NAME: arn:aws:s3:::helg9000
        run: |
          aws s3 sync build/web s3://$S3_BUCKET_NAME --delete --acl public-read
